const date=document.getElementById('date');
const day=document.getElementById('day');
const month=document.getElementById('month');
const year=document.getElementById('year');
const weekDays=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']
const allMonths=['January','Febuary','March','April','May','June',"July",'Agust','Spetember','October','November','December']
const today=new Date();
date.innerHTML=(today.getDate()<10?'0':'') + today.getDate();
day.innerHTML=weekDays[today.getDay()];
month.innerHTML=allMonths[today.getMonth()];
year.innerHTML=today.getFullYear()
